### ISSUE TITLE
Test state sync feature

### ISSUE THREAD

**Issue by EG-easy** [cosmos-gaminghub/nibiru#114]
# Description

Test state stnc feature

## Required Tasks
- [x] test state sync

**Comment by EG-easy** [comment]
ref: https://blog.cosmos.network/cosmos-sdk-state-sync-guide-99e4cf43be2f

**Comment by padi-dev-hoangpa** [comment]
Test done.
![Screen Shot 2022-01-13 at 4 13 34 PM](https://user-images.githubusercontent.com/50005242/149302071-9f1f44d2-e280-40b1-97b4-91a12c19410d.png)
