### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by tak1827** [cosmos-gaminghub/nibiru#46]
The `nibirud` version should be `0.1.0` after launch,
but now is `0.3.1`.

This version is coming from the latest `git tag`.
It' better to clear all tags.

**Comment by EG-easy** [comment]
We have already used tag `0.3` in nibiru-2000 testnet and instruction docs. 
So I would like to continue to use this versioning. 

How about using `1.0.0` for mainnet launch?

**Comment by tak1827** [comment]
I see, thank you for replaying.
